name: JS Login Form Test Runner

on:
  pull_request_target:
    branches: ["main"]

jobs:
  js_login_form_test_runner:
    uses: developer-job-simulation/javascript-login-form-tests/main.yml@main
    with:
      pr_number: ${{ github.event.pull_request.number }}
      head_sha: ${{ github.event.pull_request.head.sha }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
